// <auto-generated />
namespace _024.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class v01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v01));
        
        string IMigrationMetadata.Id
        {
            get { return "201503281726098_v01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
